### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by otamam818** [otamam818/NoteMaker#9]
# Generic
- [x] Save: `CTRL+S`
- [x] Load: `CTTRL+O`
- [x] Help: `CTRL+H`

# Specific  
## Open new windows
- [x] Customize: `CTRL+Q`  
## Task-related
- [ ] Task in current line completed: `CTRL+Down`
- [ ] Task in current line not completed: `CTRL+Up`  
## Line-related
- [ ] Move line up: `ALT+Up`
- [ ] Move line down: `ALT+Down`  
## Adding stuff into the textbox
- [ ] Add to-do/checkbox: `ALT+C`
- [ ] Add bullet: `ALT+B`
- [ ] Add title: `ALT+T`
